### ISSUE TITLE
Tracker Issue for merging new config/scripting system

### ISSUE THREAD

**Issue by OlsonZacheryFS** [FamilySearch/pewpew#126]
Tracker Issue for things that need to be fixed for the https://github.com/OlsonZacheryFS/pewpew/tree/try-merge-new-config branch.

- [ ] Multiple scripting helper functions still need to be reimplemented.
  - [x] `parseInt`
  - [x] `parseFloat`
  - [x] `repeat`
  - [x] `end_pad`
  - [ ] Behavior of `collect()` will likely need to be done differently.
- [ ] Expressions page in book
- [ ] Integration tests need to be updated.
